class XtdGearInfos {
    class CfgVehicles {
         #include "XtdGearInfos\BRM\CfgVehicles\BRM_PatrolBP.hpp"
         #include "XtdGearInfos\BRM\CfgVehicles\BRM_PatrolBPH.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_LRRBP.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_PatrolBPHLR.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_PatrolBPLR.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_SqBackpack.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_SqBpEXPLO.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_SqBpEXPLOH.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgVehicles\BRM_SqBpH.hpp"
    };
    class CfgWeapons {
         #include "XtdGearInfos\BRM\CfgWeapons\BMR_MLBV.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BMR_MLBVARMOR.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_6B.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_6B7.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_ACH.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_BattleUNI.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_BattleUNIFLC.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_BattleUNIRS.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_BattleUNIT.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_Boonie.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_BoonieCOMS.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_EBattleUNI.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_EBattleUNIRS.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_EBattleUNITS.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_fieldcap.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_Gorka.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_IBA.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_IBA_ALICE.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_LBT.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_LWH.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_M1H.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_M56.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_Parka.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_PASGT.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_PatrolCap.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_Protec.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_RRV.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_SOVWEB.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\U_BRM.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\U_BRM_Fleece.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\U_BRM_RS.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\U_BRM_Shirt.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\U_BRM_U.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_Beanie.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_BeanieCOMS.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_Beret2.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_BeretPELTOR.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_capPELTOR.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_CVCSF.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_DenimT.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_PELTOR.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_SPH4.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_SPH4V.hpp"
         #include "XtdGearInfos\BRM_MODELS\CfgWeapons\BRM_VZ53.hpp"
         #include "XtdGearInfos\BRM_required\CfgWeapons\BRM_ChestrigLite.hpp"
         #include "XtdGearInfos\BRM_SolidColors\CfgWeapons\BRM_capHP.hpp"
         #include "XtdGearInfos\BRM\CfgWeapons\BRM_ALICE.hpp"
    };
};
