class BRM_LBT
{
    options[] = { "camo", "camo1", "camo2" }; // Always computed, do not edit
    label = "BRM_LBT";
    class camo
    {
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_GLAK", "BLACK_MED", "BLACK_MEDAK", "BLACK_MG", "BLACK_RFL", "BLACK_RFLAK", "BLACK_SL", "BLACK_SLAK", "BLACK_TL", "BLACK_TLAK", "BROWN_GL", "BROWN_GLAK", "BROWN_MED", "BROWN_MEDAK", "BROWN_MG", "BROWN_RFL", "BROWN_RFLAK", "BROWN_SL", "BROWN_SLAK", "BROWN_TL", "BROWN_TLAK", "EMR_GLAK", "EMR_MEDAK", "EMR_MG", "EMR_RFLAK", "EMR_SLAK", "EMR_TLAK", "GREEN_GL", "GREEN_GLAK", "GREEN_MED", "GREEN_MEDAK", "GREEN_MG", "GREEN_RFL", "GREEN_RFLAK", "GREEN_SL", "GREEN_SLAK", "GREEN_TL", "GREEN_TLAK", "MLTCAM_GL", "MLTCAM_GLAK", "MLTCAM_MED", "MLTCAM_MEDAK", "MLTCAM_MG", "MLTCAM_RFL", "MLTCAM_RFLAK", "MLTCAM_SL", "MLTCAM_SLAK", "MLTCAM_TL", "MLTCAM_TLAK" }; // Always computed, do not edit
    };
    class camo1
    {
        label = "camo1";
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_GLAK", "BLACK_MED", "BLACK_MEDAK", "BLACK_MG", "BLACK_RFL", "BLACK_RFLAK", "BLACK_SL", "BLACK_SLAK", "BLACK_TL", "BLACK_TLAK", "BROWN_GLAK", "BROWN_MED", "BROWN_MEDAK", "BROWN_MG", "BROWN_RFL", "BROWN_RFLAK", "BROWN_SL", "BROWN_SLAK", "BROWN_TL", "BROWN_TLAK", "EMR_GLAK", "EMR_MEDAK", "EMR_MG", "EMR_RFLAK", "EMR_SLAK", "EMR_TLAK", "GL", "GREEN_GLAK", "GREEN_MED", "GREEN_MEDAK", "GREEN_MG", "GREEN_RFL", "GREEN_RFLAK", "GREEN_SL", "GREEN_SLAK", "GREEN_TL", "GREEN_TLAK", "MLTCAM_GLAK", "MLTCAM_MED", "MLTCAM_MEDAK", "MLTCAM_MG", "MLTCAM_RFL", "MLTCAM_RFLAK", "MLTCAM_SL", "MLTCAM_SLAK", "MLTCAM_TL", "MLTCAM_TLAK" }; // Always computed, do not edit
    };
    class camo2
    {
        label = "camo2";
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_GLAK", "BLACK_MED", "BLACK_MEDAK", "BLACK_MG", "BLACK_RFL", "BLACK_RFLAK", "BLACK_SL", "BLACK_SLAK", "BLACK_TL", "BLACK_TLAK", "BROWN_GL", "BROWN_GLAK", "BROWN_MED", "BROWN_MEDAK", "BROWN_MG", "BROWN_RFL", "BROWN_RFLAK", "BROWN_SL", "BROWN_SLAK", "BROWN_TL", "BROWN_TLAK", "EMR_GLAK", "EMR_MEDAK", "EMR_MG", "EMR_RFLAK", "EMR_SLAK", "EMR_TLAK", "GREEN_GL", "GREEN_GLAK", "GREEN_MED", "GREEN_MEDAK", "GREEN_MG", "GREEN_RFL", "GREEN_RFLAK", "GREEN_SL", "GREEN_SLAK", "GREEN_TL", "GREEN_TLAK", "MLTCAM_GL", "MLTCAM_GLAK", "MLTCAM_MED", "MLTCAM_MEDAK", "MLTCAM_MG", "MLTCAM_RFL", "MLTCAM_RFLAK", "MLTCAM_SL", "MLTCAM_SLAK", "MLTCAM_TL", "MLTCAM_TLAK" }; // Always computed, do not edit
    };
};
