class BRM_RRV
{
    options[] = { "camo", "camo1", "camob" }; // Always computed, do not edit
    label = "BRM_RRV";
    class camo
    {
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_MED", "BLACK_MG", "BLACK_REC1", "BLACK_REC2", "BLACK_RECLEAD", "BLACK_RECMED", "BLACK_RFL", "BLACK_SL", "BLACK_TL", "BROWN_GL", "BROWN_MED", "BROWN_MG", "BROWN_REC1", "BROWN_REC2", "BROWN_RECLEAD", "BROWN_RECMED", "BROWN_RFL", "BROWN_SL", "BROWN_TL", "EMR_GL", "EMR_MED", "EMR_MG", "EMR_REC1", "EMR_REC2", "EMR_RECLEAD", "EMR_RECMED", "EMR_RFL", "EMR_SL", "EMR_TL", "GREEN_GL", "GREEN_MED", "GREEN_MG", "GREEN_REC1", "GREEN_REC2", "GREEN_RECLEAD", "GREEN_RECMED", "GREEN_RFL", "GREEN_SL", "GREEN_TL", "MLTCAM_GL", "MLTCAM_MED", "MLTCAM_MG", "MLTCAM_REC1", "MLTCAM_REC2", "MLTCAM_RECLEAD", "MLTCAM_RECMED", "MLTCAM_RFL", "MLTCAM_SL", "MLTCAM_TL", "SyrDIGI_GL", "SyrDIGI_MED", "SyrDIGI_MG", "SyrDIGI_REC1", "SyrDIGI_REC2", "SyrDIGI_RECLEAD", "SyrDIGI_RECMED", "SyrDIGI_RFL", "SyrDIGI_SL", "SyrDIGI_TL" }; // Always computed, do not edit
    };
    class camo1
    {
        label = "camo1";
        alwaysSelectable = 1;
        values[] = { "BLACK_MED", "BLACK_REC1", "BLACK_REC2", "BLACK_RECLEAD", "BLACK_RECMED", "BLACK_RFL", "BLACK_SL", "BLACK_TL", "BROWN_MED", "BROWN_REC1", "BROWN_REC2", "BROWN_RECLEAD", "BROWN_RECMED", "BROWN_RFL", "BROWN_SL", "BROWN_TL", "EMR_MED", "EMR_REC1", "EMR_REC2", "EMR_RECLEAD", "EMR_RECMED", "EMR_RFL", "EMR_SL", "EMR_TL", "GL", "GREEN_GL", "GREEN_MED", "GREEN_REC1", "GREEN_REC2", "GREEN_RECLEAD", "GREEN_RECMED", "GREEN_RFL", "GREEN_SL", "GREEN_TL", "MLTCAM_MED", "MLTCAM_REC1", "MLTCAM_REC2", "MLTCAM_RECLEAD", "MLTCAM_RECMED", "MLTCAM_RFL", "MLTCAM_SL", "MLTCAM_TL", "none", "SyrDIGI_MED", "SyrDIGI_REC1", "SyrDIGI_REC2", "SyrDIGI_RECLEAD", "SyrDIGI_RECMED", "SyrDIGI_RFL", "SyrDIGI_SL", "SyrDIGI_TL" }; // Always computed, do not edit
    };
    class camob
    {
        label = "camob";
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_MED", "BLACK_MG", "BLACK_REC1", "BLACK_REC2", "BLACK_RECLEAD", "BLACK_RECMED", "BLACK_RFL", "BLACK_SL", "BLACK_TL", "BROWN_GL", "BROWN_MED", "BROWN_MG", "BROWN_REC1", "BROWN_REC2", "BROWN_RECLEAD", "BROWN_RECMED", "BROWN_RFL", "BROWN_SL", "BROWN_TL", "EMR_GL", "EMR_MED", "EMR_MG", "EMR_REC1", "EMR_REC2", "EMR_RECLEAD", "EMR_RECMED", "EMR_RFL", "EMR_SL", "EMR_TL", "GREEN_GL", "GREEN_MED", "GREEN_MG", "GREEN_REC1", "GREEN_REC2", "GREEN_RECLEAD", "GREEN_RECMED", "GREEN_RFL", "GREEN_SL", "GREEN_TL", "MLTCAM_GL", "MLTCAM_MED", "MLTCAM_MG", "MLTCAM_REC1", "MLTCAM_REC2", "MLTCAM_RECLEAD", "MLTCAM_RECMED", "MLTCAM_RFL", "MLTCAM_SL", "MLTCAM_TL", "SyrDIGI_GL", "SyrDIGI_MED", "SyrDIGI_MG", "SyrDIGI_REC1", "SyrDIGI_REC2", "SyrDIGI_RECLEAD", "SyrDIGI_RECMED", "SyrDIGI_RFL", "SyrDIGI_SL", "SyrDIGI_TL" }; // Always computed, do not edit
    };
};
