class BRM_Protec
{
    options[] = { "camo", "camo1", "camob" }; // Always computed, do not edit
    label = "BRM_Protec";
    class camo
    {
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_HeavyGL", "BLACK_HeavyRFL", "BLACK_MG", "BLACK_RFL", "BLACK_SL", "BLACK_TL", "BROWN_GL", "BROWN_HeavyGL", "BROWN_HeavyRFL", "BROWN_MG", "BROWN_RFL", "BROWN_SL", "BROWN_TL", "CADPATD_GL", "CADPATD_HeavyGL", "CADPATD_HeavyRFL", "CADPATD_MG", "CADPATD_RFL", "CADPATD_SL", "CADPATD_TL", "CADPATW_GL", "CADPATW_HeavyGL", "CADPATW_HeavyRFL", "CADPATW_MG", "CADPATW_RFL", "CADPATW_SL", "CADPATW_TL", "DFRACD_GL", "DFRACD_HeavyGL", "DFRACD_HeavyRFL", "DFRACD_MG", "DFRACD_RFL", "DFRACD_SL", "DFRACD_TL", "DFRACW_GL", "DFRACW_HeavyGL", "DFRACW_HeavyRFL", "DFRACW_MG", "DFRACW_RFL", "DFRACW_SL", "DFRACW_TL", "DPCU_GL", "DPCU_HeavyGL", "DPCU_HeavyRFL", "DPCU_MG", "DPCU_RFL", "DPCU_SL", "DPCU_TL", "DPDU_GL", "DPDU_HeavyGL", "DPDU_HeavyRFL", "DPDU_MG", "DPDU_RFL", "DPDU_SL", "DPDU_TL", "ESTDCU_GL", "ESTDCU_HeavyGL", "ESTDCU_HeavyRFL", "ESTDCU_MG", "ESTDCU_RFL", "ESTDCU_SL", "ESTDCU_TL", "FLECK_GL", "FLECK_HeavyGL", "FLECK_HeavyRFL", "FLECK_MG", "FLECK_RFL", "FLECK_SL", "FLECK_TL", "GraniteB_GL", "GraniteB_HeavyGL", "GraniteB_HeavyRFL", "GraniteB_MG", "GraniteB_RFL", "GraniteB_SL", "GraniteB_TL", "GREEN_GL", "GREEN_HeavyGL", "GREEN_HeavyRFL", "GREEN_MG", "GREEN_RFL", "GREEN_SL", "GREEN_TL", "JIEITAIW_GL", "JIEITAIW_HeavyGL", "JIEITAIW_HeavyRFL", "JIEITAIW_MG", "JIEITAIW_RFL", "JIEITAIW_SL", "JIEITAIW_TL", "ROKMC_GL", "ROKMC_HeavyGL", "ROKMC_HeavyRFL", "ROKMC_MG", "ROKMC_RFL", "ROKMC_SL", "ROKMC_TL", "TROPEN_GL", "TROPEN_HeavyGL", "TROPEN_HeavyRFL", "TROPEN_MG", "TROPEN_RFL", "TROPEN_SL", "TROPEN_TL" }; // Always computed, do not edit
    };
    class camo1
    {
        label = "camo1";
        alwaysSelectable = 1;
        values[] = { "BLACK_HeavyGL", "BLACK_HeavyRFL", "BLACK_RFL", "BLACK_SL", "BLACK_TL", "BROWN_HeavyGL", "BROWN_HeavyRFL", "BROWN_RFL", "BROWN_SL", "BROWN_TL", "CADPATD_HeavyGL", "CADPATD_HeavyRFL", "CADPATD_RFL", "CADPATD_SL", "CADPATD_TL", "CADPATW_HeavyGL", "CADPATW_HeavyRFL", "CADPATW_RFL", "CADPATW_SL", "CADPATW_TL", "DFRACD_HeavyGL", "DFRACD_HeavyRFL", "DFRACD_RFL", "DFRACD_SL", "DFRACD_TL", "DFRACW_HeavyGL", "DFRACW_HeavyRFL", "DFRACW_RFL", "DFRACW_SL", "DFRACW_TL", "DPCU_HeavyGL", "DPCU_HeavyRFL", "DPCU_RFL", "DPCU_SL", "DPCU_TL", "DPDU_HeavyGL", "DPDU_HeavyRFL", "DPDU_RFL", "DPDU_SL", "DPDU_TL", "ESTDCU_HeavyGL", "ESTDCU_HeavyRFL", "ESTDCU_RFL", "ESTDCU_SL", "ESTDCU_TL", "FLECK_HeavyGL", "FLECK_HeavyRFL", "FLECK_RFL", "FLECK_SL", "FLECK_TL", "GraniteB_HeavyGL", "GraniteB_HeavyRFL", "GraniteB_RFL", "GraniteB_SL", "GraniteB_TL", "GREEN_HeavyGL", "GREEN_HeavyRFL", "GREEN_RFL", "GREEN_SL", "GREEN_TL", "JIEITAIW_HeavyGL", "JIEITAIW_HeavyRFL", "JIEITAIW_RFL", "JIEITAIW_SL", "JIEITAIW_TL", "none", "ROKMC_HeavyGL", "ROKMC_HeavyRFL", "ROKMC_RFL", "ROKMC_SL", "ROKMC_TL", "TROPEN_HeavyGL", "TROPEN_HeavyRFL", "TROPEN_RFL", "TROPEN_SL", "TROPEN_TL" }; // Always computed, do not edit
    };
    class camob
    {
        label = "camob";
        alwaysSelectable = 1;
        values[] = { "BLACK_GL", "BLACK_HeavyGL", "BLACK_HeavyRFL", "BLACK_MG", "BLACK_RFL", "BLACK_SL", "BLACK_TL", "BROWN_GL", "BROWN_HeavyGL", "BROWN_HeavyRFL", "BROWN_MG", "BROWN_RFL", "BROWN_SL", "BROWN_TL", "CADPATD_GL", "CADPATD_HeavyGL", "CADPATD_HeavyRFL", "CADPATD_MG", "CADPATD_RFL", "CADPATD_SL", "CADPATD_TL", "CADPATW_GL", "CADPATW_HeavyGL", "CADPATW_HeavyRFL", "CADPATW_MG", "CADPATW_RFL", "CADPATW_SL", "CADPATW_TL", "DFRACD_GL", "DFRACD_HeavyGL", "DFRACD_HeavyRFL", "DFRACD_MG", "DFRACD_RFL", "DFRACD_SL", "DFRACD_TL", "DFRACW_GL", "DFRACW_HeavyGL", "DFRACW_HeavyRFL", "DFRACW_MG", "DFRACW_RFL", "DFRACW_SL", "DFRACW_TL", "DPCU_GL", "DPCU_HeavyGL", "DPCU_HeavyRFL", "DPCU_MG", "DPCU_RFL", "DPCU_SL", "DPCU_TL", "DPDU_GL", "DPDU_HeavyGL", "DPDU_HeavyRFL", "DPDU_MG", "DPDU_RFL", "DPDU_SL", "DPDU_TL", "ESTDCU_GL", "ESTDCU_HeavyGL", "ESTDCU_HeavyRFL", "ESTDCU_MG", "ESTDCU_RFL", "ESTDCU_SL", "ESTDCU_TL", "FLECK_GL", "FLECK_HeavyGL", "FLECK_HeavyRFL", "FLECK_MG", "FLECK_RFL", "FLECK_SL", "FLECK_TL", "GraniteB_GL", "GraniteB_HeavyGL", "GraniteB_HeavyRFL", "GraniteB_MG", "GraniteB_RFL", "GraniteB_SL", "GraniteB_TL", "GREEN_GL", "GREEN_HeavyGL", "GREEN_HeavyRFL", "GREEN_MG", "GREEN_RFL", "GREEN_SL", "GREEN_TL", "JIEITAIW_GL", "JIEITAIW_HeavyGL", "JIEITAIW_HeavyRFL", "JIEITAIW_MG", "JIEITAIW_RFL", "JIEITAIW_SL", "JIEITAIW_TL", "ROKMC_GL", "ROKMC_HeavyGL", "ROKMC_HeavyRFL", "ROKMC_MG", "ROKMC_RFL", "ROKMC_SL", "ROKMC_TL", "TROPEN_GL", "TROPEN_HeavyGL", "TROPEN_HeavyRFL", "TROPEN_MG", "TROPEN_RFL", "TROPEN_SL", "TROPEN_TL" }; // Always computed, do not edit
    };
};
